# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  azureServiceConnection: 'MVP-Subscription'
  resourceGroupName: 'rg-BicepTemplate-Demo'
  location: 'westeurope'
  templateFile: './36_Azure_ARM-Development/ARM_Template/deploy.json'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'pscore'
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)


